"""add whatsapp messages table

Revision ID: c2b9f4d83a51
Revises: f3a7c91b04e2
Create Date: 2026-04-28 06:00:00.000000

Creates the `whatsapp_messages` table used by the inbound webhook
handler. Touches no existing tables. Downgrade drops only the new
table and its indexes.

NOTE: written by hand (not autogenerated) so it is provably scoped to
a single new table — no implicit schema drift, no autogen surprises.
Same pattern as f3a7c91b04e2 (audit log V1).
"""
from alembic import op
import sqlalchemy as sa


revision = 'c2b9f4d83a51'
down_revision = 'f3a7c91b04e2'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'whatsapp_messages',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('direction', sa.String(length=10), nullable=False),
        sa.Column('wa_message_id', sa.String(length=128), nullable=True),
        sa.Column('wa_timestamp', sa.DateTime(), nullable=True),
        sa.Column('from_phone_hash', sa.String(length=64), nullable=True),
        sa.Column('from_phone_last4', sa.String(length=8), nullable=True),
        sa.Column('to_phone_last4', sa.String(length=8), nullable=True),
        sa.Column('profile_name', sa.String(length=100), nullable=True),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('guest_id', sa.Integer(), nullable=True),
        sa.Column('message_type', sa.String(length=30), nullable=False),
        sa.Column('body_text', sa.Text(), nullable=True),
        sa.Column('body_preview', sa.String(length=120), nullable=True),
        sa.Column('status', sa.String(length=20),
                  nullable=True, server_default='received'),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.UniqueConstraint('wa_message_id',
                            name='uq_whatsapp_messages_wa_message_id'),
        sa.ForeignKeyConstraint(
            ['booking_id'], ['bookings.id'],
            ondelete='SET NULL',
            name='fk_whatsapp_messages_booking_id',
        ),
        sa.ForeignKeyConstraint(
            ['guest_id'], ['guests.id'],
            ondelete='SET NULL',
            name='fk_whatsapp_messages_guest_id',
        ),
    )
    op.create_index(
        'ix_whatsapp_messages_created_at',
        'whatsapp_messages', ['created_at'], unique=False,
    )
    op.create_index(
        'ix_wa_messages_booking_created',
        'whatsapp_messages', ['booking_id', 'created_at'], unique=False,
    )
    op.create_index(
        'ix_wa_messages_guest_created',
        'whatsapp_messages', ['guest_id', 'created_at'], unique=False,
    )
    op.create_index(
        'ix_wa_messages_direction_created',
        'whatsapp_messages', ['direction', 'created_at'], unique=False,
    )
    op.create_index(
        'ix_wa_messages_from_phone_hash',
        'whatsapp_messages', ['from_phone_hash'], unique=False,
    )


def downgrade():
    op.drop_index('ix_wa_messages_from_phone_hash',
                  table_name='whatsapp_messages')
    op.drop_index('ix_wa_messages_direction_created',
                  table_name='whatsapp_messages')
    op.drop_index('ix_wa_messages_guest_created',
                  table_name='whatsapp_messages')
    op.drop_index('ix_wa_messages_booking_created',
                  table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_created_at',
                  table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
