"""add folio items table

Revision ID: d8a3e1f29c40
Revises: c2b9f4d83a51
Create Date: 2026-04-29 03:38:00.000000

Creates the `folio_items` table for Guest Folio V1 — the running
account of charges, discounts, payments, and adjustments per booking.
Touches no existing tables. Downgrade drops only the new table and
its indexes/FKs.

NOTE: hand-written (not autogenerated) so this revision is provably
scoped to a single new table — no implicit schema drift. Same pattern
as f3a7c91b04e2 (audit log) and c2b9f4d83a51 (whatsapp messages).

Folio V1 design rules:
- Folio is ADDITIVE for extras only. Room revenue stays on bookings.total_amount.
- total_amount is stored SIGNED (charges positive, payments / discounts negative).
- Items are NEVER hard-deleted. status='voided' marks an undo with full audit trail.
- See app/services/folio.py for the canonical enums + balance math.
"""
from alembic import op
import sqlalchemy as sa


revision = 'd8a3e1f29c40'
down_revision = 'c2b9f4d83a51'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'folio_items',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),

        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),

        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('guest_id',   sa.Integer(), nullable=True),
        sa.Column('invoice_id', sa.Integer(), nullable=True),

        sa.Column('item_type',   sa.String(length=30),  nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),

        sa.Column('quantity',              sa.Float(), nullable=False,
                  server_default='1.0'),
        sa.Column('unit_price',            sa.Float(), nullable=False,
                  server_default='0.0'),
        sa.Column('amount',                sa.Float(), nullable=False,
                  server_default='0.0'),
        sa.Column('tax_amount',            sa.Float(), nullable=False,
                  server_default='0.0'),
        sa.Column('service_charge_amount', sa.Float(), nullable=False,
                  server_default='0.0'),
        sa.Column('total_amount',          sa.Float(), nullable=False,
                  server_default='0.0'),

        sa.Column('status',        sa.String(length=20), nullable=False,
                  server_default='open'),
        sa.Column('source_module', sa.String(length=20), nullable=False,
                  server_default='manual'),

        sa.Column('posted_by_user_id', sa.Integer(), nullable=True),

        sa.Column('voided_at',         sa.DateTime(), nullable=True),
        sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
        sa.Column('void_reason',       sa.String(length=255), nullable=True),

        sa.Column('metadata_json', sa.Text(), nullable=True),

        sa.ForeignKeyConstraint(
            ['booking_id'], ['bookings.id'],
            name='fk_folio_items_booking_id_bookings',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['guest_id'], ['guests.id'],
            name='fk_folio_items_guest_id_guests',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['invoice_id'], ['invoices.id'],
            name='fk_folio_items_invoice_id_invoices',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['posted_by_user_id'], ['users.id'],
            name='fk_folio_items_posted_by_user_id_users',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['voided_by_user_id'], ['users.id'],
            name='fk_folio_items_voided_by_user_id_users',
            ondelete='SET NULL',
        ),
    )

    op.create_index('ix_folio_items_created_at',
                    'folio_items', ['created_at'])
    op.create_index('ix_folio_items_booking_created',
                    'folio_items', ['booking_id', 'created_at'])
    op.create_index('ix_folio_items_guest_created',
                    'folio_items', ['guest_id', 'created_at'])
    op.create_index('ix_folio_items_invoice',
                    'folio_items', ['invoice_id'])
    op.create_index('ix_folio_items_status',
                    'folio_items', ['status'])


def downgrade():
    op.drop_index('ix_folio_items_status',          table_name='folio_items')
    op.drop_index('ix_folio_items_invoice',         table_name='folio_items')
    op.drop_index('ix_folio_items_guest_created',   table_name='folio_items')
    op.drop_index('ix_folio_items_booking_created', table_name='folio_items')
    op.drop_index('ix_folio_items_created_at',      table_name='folio_items')
    op.drop_table('folio_items')
