"""add room blocks table

Revision ID: e7c1a4b89d62
Revises: d8a3e1f29c40
Create Date: 2026-04-29 12:00:00.000000

Creates the `room_blocks` table — date-ranged out-of-order / owner-hold
periods per room. Touches no existing tables. Downgrade drops only the
new table and its indexes/FKs.

Hand-written (not autogenerated) so this revision is provably scoped to
a single new table — no implicit schema drift. Same convention as the
prior migrations f3a7c91b04e2, c2b9f4d83a51, d8a3e1f29c40.
"""
from alembic import op
import sqlalchemy as sa


revision = 'e7c1a4b89d62'
down_revision = 'd8a3e1f29c40'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'room_blocks',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('room_id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('reason', sa.String(length=40), nullable=False,
                  server_default='maintenance'),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.Column('removed_at', sa.DateTime(), nullable=True),
        sa.Column('removed_by_user_id', sa.Integer(), nullable=True),

        sa.ForeignKeyConstraint(
            ['room_id'], ['rooms.id'],
            name='fk_room_blocks_room_id_rooms',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['created_by_user_id'], ['users.id'],
            name='fk_room_blocks_created_by_users',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['removed_by_user_id'], ['users.id'],
            name='fk_room_blocks_removed_by_users',
            ondelete='SET NULL',
        ),
    )

    op.create_index('ix_room_blocks_created_at',
                    'room_blocks', ['created_at'])
    op.create_index('ix_room_blocks_room_dates',
                    'room_blocks', ['room_id', 'start_date', 'end_date'])
    op.create_index('ix_room_blocks_active',
                    'room_blocks', ['room_id', 'removed_at'])


def downgrade():
    op.drop_index('ix_room_blocks_active',     table_name='room_blocks')
    op.drop_index('ix_room_blocks_room_dates', table_name='room_blocks')
    op.drop_index('ix_room_blocks_created_at', table_name='room_blocks')
    op.drop_table('room_blocks')
