"""add cashier transactions table

Revision ID: f1c5b2a93e80
Revises: e7c1a4b89d62
Create Date: 2026-04-29 14:30:00.000000

Creates the `cashier_transactions` table for Cashiering V1 — the
cash-event ledger that captures how a payment was received (method,
reference, cashier) separate from the FolioItem ledger.

Hand-written (not autogenerated). Touches no existing tables.
Downgrade drops only the new table and its indexes/FKs.

Same convention as the prior migrations: f3a7c91b04e2 (audit log),
c2b9f4d83a51 (whatsapp messages), d8a3e1f29c40 (folio items),
e7c1a4b89d62 (room blocks).

Cashiering V1 design rules (binding, see app/models.py::CashierTransaction):
- amount stored POSITIVE; direction is on transaction_type
- folio_item_id links to the FolioItem this transaction created
- voiding sets status='voided'; row preserved for audit
- V1 does NOT modify Invoice.amount_paid — that's Phase 4 work
"""
from alembic import op
import sqlalchemy as sa


revision = 'f1c5b2a93e80'
down_revision = 'e7c1a4b89d62'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'cashier_transactions',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),

        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('guest_id',   sa.Integer(), nullable=True),
        sa.Column('folio_item_id', sa.Integer(), nullable=True),
        sa.Column('invoice_id', sa.Integer(), nullable=True),

        sa.Column('amount',   sa.Float(), nullable=False,
                  server_default='0.0'),
        sa.Column('currency', sa.String(length=3), nullable=False,
                  server_default='MVR'),

        sa.Column('payment_method',   sa.String(length=20), nullable=False),
        sa.Column('reference_number', sa.String(length=80), nullable=True),

        sa.Column('received_by_user_id', sa.Integer(), nullable=True),

        sa.Column('transaction_type', sa.String(length=20), nullable=False,
                  server_default='payment'),
        sa.Column('status', sa.String(length=20), nullable=False,
                  server_default='posted'),

        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('metadata_json', sa.Text(), nullable=True),

        sa.Column('voided_at', sa.DateTime(), nullable=True),
        sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
        sa.Column('void_reason', sa.String(length=255), nullable=True),

        sa.ForeignKeyConstraint(
            ['booking_id'], ['bookings.id'],
            name='fk_cashier_txn_booking',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['guest_id'], ['guests.id'],
            name='fk_cashier_txn_guest',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['folio_item_id'], ['folio_items.id'],
            name='fk_cashier_txn_folio_item',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['invoice_id'], ['invoices.id'],
            name='fk_cashier_txn_invoice',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['received_by_user_id'], ['users.id'],
            name='fk_cashier_txn_received_by',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['voided_by_user_id'], ['users.id'],
            name='fk_cashier_txn_voided_by',
            ondelete='SET NULL',
        ),
    )

    op.create_index('ix_cashier_txn_created_at',
                    'cashier_transactions', ['created_at'])
    op.create_index('ix_cashier_txn_booking_created',
                    'cashier_transactions', ['booking_id', 'created_at'])
    op.create_index('ix_cashier_txn_user_created',
                    'cashier_transactions',
                    ['received_by_user_id', 'created_at'])
    op.create_index('ix_cashier_txn_status',
                    'cashier_transactions', ['status'])
    op.create_index('ix_cashier_txn_method',
                    'cashier_transactions', ['payment_method'])


def downgrade():
    op.drop_index('ix_cashier_txn_method',          table_name='cashier_transactions')
    op.drop_index('ix_cashier_txn_status',          table_name='cashier_transactions')
    op.drop_index('ix_cashier_txn_user_created',    table_name='cashier_transactions')
    op.drop_index('ix_cashier_txn_booking_created', table_name='cashier_transactions')
    op.drop_index('ix_cashier_txn_created_at',      table_name='cashier_transactions')
    op.drop_table('cashier_transactions')
