"""add activity log table

Revision ID: f3a7c91b04e2
Revises: e4f7a2b1c8d3
Create Date: 2026-04-27 07:10:00.000000

Creates the append-only `activity_logs` table used by the audit/activity
log system. Touches no existing tables. Downgrade drops only the new
table and its indexes.

NOTE: written by hand (not autogenerated) so it is provably scoped to a
single new table — no implicit schema drift, no autogen surprises.
"""
from alembic import op
import sqlalchemy as sa


revision = 'f3a7c91b04e2'
down_revision = 'e4f7a2b1c8d3'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'activity_logs',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('actor_type', sa.String(length=20), nullable=False),
        sa.Column('actor_user_id', sa.Integer(), nullable=True),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('invoice_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=64), nullable=False),
        sa.Column('old_value', sa.String(length=64), nullable=True),
        sa.Column('new_value', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=False,
                  server_default=''),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ['actor_user_id'], ['users.id'],
            ondelete='SET NULL',
            name='fk_activity_logs_actor_user_id',
        ),
        sa.ForeignKeyConstraint(
            ['booking_id'], ['bookings.id'],
            ondelete='SET NULL',
            name='fk_activity_logs_booking_id',
        ),
        sa.ForeignKeyConstraint(
            ['invoice_id'], ['invoices.id'],
            ondelete='SET NULL',
            name='fk_activity_logs_invoice_id',
        ),
    )
    op.create_index(
        'ix_activity_logs_created_at',
        'activity_logs', ['created_at'], unique=False,
    )
    op.create_index(
        'ix_activity_logs_booking_created',
        'activity_logs', ['booking_id', 'created_at'], unique=False,
    )
    op.create_index(
        'ix_activity_logs_invoice_created',
        'activity_logs', ['invoice_id', 'created_at'], unique=False,
    )
    op.create_index(
        'ix_activity_logs_action_created',
        'activity_logs', ['action', 'created_at'], unique=False,
    )


def downgrade():
    op.drop_index('ix_activity_logs_action_created', table_name='activity_logs')
    op.drop_index('ix_activity_logs_invoice_created', table_name='activity_logs')
    op.drop_index('ix_activity_logs_booking_created', table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.drop_table('activity_logs')
